server:
  port: 1111
# eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    # 不允许eurekaServer 作为服务向 eurekaServer注册
    register-with-eureka: false
    # 禁止eurekaServer进行检索服务
    fetch-registry: false
  instance:
    hostname: localhost
