# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8082/eureka/,http://peer3:8083/eureka/
# spring
spring:
  application:
    name: hello-orcas-service
# 自定义
hello: Hello World!