# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    # 定义服务失效的时间，默认90s
    lease-expiration-duration-in-seconds: 90
    # 定义服务续约任务的调用间隔时间，默认30s
    lease-renewal-interval-in-seconds: 30
# spring
spring:
  application:
    # 服务名称
    name: hello-orcas-service
# 自定义
hello: Hello World!
# 日志配置文件路径
logging:
  path: classpath:logback.xml